apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomato
  labels:
    app: zomato
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
      labels:
        app: zomato
    spec:
      containers:
      - name: zomato
        image: 121846058083.dkr.ecr.us-east-1.amazonaws.com/zomato-app:latest
        ports:
        - containerPort: 3000
